function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BALLANDBEAMODEMATRICES
%    [W,RHS] = BALLANDBEAMODEMATRICES(IN1,TO,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Feb-2021 13:55:09

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
dx = in1(3,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t5 = t3.^2;
t6 = M.*R.*t5.*(7.0./5.0);
t7 = -t6;
W = reshape([M.*(7.0./5.0),t7,t7,J+M.*(R.*t3-t2.*x).^2.*(7.0./5.0)+M.*t5.*x.^2.*(7.0./5.0)],[2,2]);
if nargout > 1
    RHS = [M.*(g.*t3.*1.0e+1+t4.*x.*1.4e+1-R.*t4.*sin(theta.*2.0).*7.0).*(-1.0./1.0e+1);To+(M.*(R.*g.*t3.*5.0-g.*t2.*x.*5.0+R.*t4.*x.*(t2.^2.*2.0-1.0).*7.0-R.^2.*t2.*t3.*t4.*7.0+R.*dtheta.*dx.*t2.*t3.*1.4e+1))./5.0];
end
